# Generated by Django 5.0.2 on 2024-03-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_scheduledpost_time_socialmediahandle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
